#!/bin/sh
#
# Build an elpa package according to:
# https://wiki.debian.org/Teams/DebianEmacsenTeam/elpa-hello
#
set -eu

cd debian/tests/elpa-test
# Create a dummy .orig.tar.gz
tar czvf ../elpa-test_1.0.orig.tar.gz all.el
dpkg-buildpackage
# Make sure the ${elpa:Depends} were picked up
dpkg-deb --info ../elpa-all_1.0-1_all.deb | grep Depends | grep dh-elpa-helper
